### ISSUE TITLE
error loading pytorch 

### ISSUE THREAD

**Issue by yanbosmu** [jostorge/diffusion-hopping#4]
I installed your software successfully.
but when I use python generate_scaffolds.py, the error occurred.

Traceback (most recent call last):
  File "/home/yanbosmu/Bioinfo/diffusion-hopping-main/generate_scaffolds.py", line 4, in <module>
    import torch
  File "/home/yanbosmu/mambaforge/envs/diffusion_hopping/lib/python3.10/site-packages/torch/__init__.py", line 218, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/yanbosmu/mambaforge/envs/diffusion_hopping/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent

seems like import torch failed?
THANK YOU!

**Comment by yanbosmu** [comment]
Is that something about I used mamba forge?

**Comment by architvasan** [comment]
Yah, I had the same problem but when I followed the link posted by jostorge, this suggestion: `Please downgrade MKL <= 2024.0, or do not specify MKL version.` solved the problem for me
